spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clinica?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mvc:
    async:
      request-timeout: 60000

server:
  tomcat:
    connection-timeout: 60000
  port: 8085

# Espacio para la configuraci√≥n de groq api


# Logging para debug
logging:
  level:
    com.clinica.gestor_citas.service.GroqChatService: DEBUG
    org.springframework.web.client: DEBUG
